# Generated by Django 4.1.2 on 2022-11-06 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=7)),
                ('district', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('door_no', models.CharField(max_length=50)),
            ],
        ),
    ]
