# Generated by Django 4.1.2 on 2022-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='xxx', upload_to='product_images'),
            preserve_default=False,
        ),
    ]
