# Generated by Django 4.1.2 on 2022-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='file_path',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='file_upload',
            field=models.FileField(default='empty', upload_to='customer_files'),
            preserve_default=False,
        ),
    ]
