# Generated by Django 4.1.2 on 2022-11-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_sides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
    ]
