# Generated by Django 4.1.3 on 2022-11-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orders_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='colour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sides',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
