# Generated by Django 4.1.3 on 2022-11-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cart_colour_alter_cart_pages_alter_cart_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='colour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
