# Generated by Django 4.1.3 on 2022-11-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderdetails_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='college',
            field=models.TextField(default='Aditya College Of Engineering', max_length=30),
            preserve_default=False,
        ),
    ]
