# Generated by Django 4.1.3 on 2022-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orders_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
