# Generated by Django 4.1.3 on 2022-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Printed', 'Printed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Order Received', max_length=15),
        ),
    ]
