# Generated by Django 4.1.3 on 2023-01-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orders_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.orders')),
                ('order_id', models.TextField(unique=True)),
                ('payment_id', models.TextField(unique=True)),
                ('signature', models.TextField()),
            ],
        ),
    ]
