# Generated by Django 4.1.3 on 2023-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='sides',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
